### ISSUE TITLE
Extracting the job ID fails due to differences in case-sensitivity

### ISSUE THREAD

**Issue by mardukbp** [lars-sh/jes-client#22]
### Problem

The call to `JesClient.submit` throws the exception:

```
de.larssh.jes.JesException:  Started job, but could not extract its ID. Reason: 250-It is known to JES as J0540657
```

### Cause

The [regex pattern](https://github.com/lars-sh/jes-client/blob/master/src/main/lombok/de/larssh/jes/JesClient.java#L140) used to extract the job ID is written in all caps. 

### Solution

Add the flag `CASE_INSENSITIVE` to the regex:

```java
Pattern PATTERN_FTP_SUBMIT_ID = Pattern.compile("^250-IT IS KNOWN TO JES AS (?<id>\\S+)", Pattern.CASE_INSENSITIVE);
```

More generally, this flag should be added to the other regexes.

Thank you for writing this library!

PS: I tried to build the project, but I don't know how to do it, given its dependency on your `parent` project. It would be nice if you could document how to build it.

**Comment by lars-sh** [comment]
Thanks @mardukbp for your contribution. I tested the code with the machines I've access to only. Therefore, making patterns case-insensitive is a good idea to increase support for additional installations.

Regarding building the project from sources I just added a very short section at https://github.com/lars-sh/jes-client#building-from-sources .

Feel free to ask for support in case things don't go the way you expected.

**Comment by mardukbp** [comment]
Thank you for addressing this issue so fast! I will test it tomorrow. If all works well, I will ask you to publish the latest version on Maven Central :)

Thank you also for the addition to the README. It worked on my home computer. I guess it did not work in a corporate environment due to the Maven settings.

**Comment by lars-sh** [comment]
@mardukbp, most corporate environments don't use Maven Central directly, but put a local proxy in between. Maybes that's why it didn't work out-of-the box.

In case you're just interested in the snapshot version you might want to grab it from GitHub Packages, see https://github.com/lars-sh/jes-client/packages/607291 . A manual on using GitHub Packages with Maven is given at https://docs.github.com/de/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry .
